### ISSUE TITLE
function useGame() {

### ISSUE THREAD

**Issue by slukin1** [mudachyo/Bybit-Coinsweeper#4]
https://bybitcoinsweeper.com/assets/index-xmFDawbb.js
function useGame() {
...
...
...
            const hr = randomNumber(0, lr.length - 1)
              , dr = lr.splice(hr, 1)[0];
            dr && (dr.hasBagCoin = !0,
            dr.bagCoinImage = bagCoinImage$1)             // ******MNT here*****
        }
        return Pt                               // *******all mines here hasBomb true or hasBomb false*******
    }
    , []);
    return {
        fields: e,
        fieldsOpened: a,
        openField: er,
        initFields: ir,
        flagsCount: g,
        setFlag: ar,
        deleteFlag: rr,
        placeBagCoins: Qt,
        setFields: s
    }
}
but to find MNT we need to open all cells without bombs minus 1 and wait for MNT appering

**Comment by mudachyo** [comment]
Unfortunately, this information didn't do anything for me

**Comment by slukin1** [comment]
после первого клика В переменной Pt функции useGame() в файле assets/index-xmFDawbb.js доступен массив игрового поля с расположением мин в формате
[
    {
        "key": "[1,1]",
        "value": {
            "id": 1,
            "coords": [
                1,
                1
            ],
            "isOpened": true,
            "hasBomb": false,
            "hasFlag": false,
            "bombsAround": 0,
            "blockImage": "data:image/svg+xml,...fill='%23FF9C2E'/%3e%3c/svg%3e"
        }
    },
.
.
.
.
    {
        "key": "[6,9]",
        "value": {
            "id": 54,
            "coords": [
                2,
                1
            ],
            "isOpened": true,
            "hasBomb": false,
            "hasFlag": false,
            "bombsAround": 0,
            "blockImage": "data:image/svg+xml,...fill='%23FF9C2E'/%3e%3c/svg%3e"
        }
    }
]

а появляющиеся монеты MNT доступны через переменную dr.hasBagCoin
