### ISSUE TITLE
Перестал работать

### ISSUE THREAD

**Issue by pav18** [mudachyo/Bybit-Coinsweeper#8]
Там какие-то изменения в честь юбилея и скрипт перестал работать...

**Comment by slukin1** [comment]
change 
const gameBoardXPath = '/html/body/div[2]/section';
to
const gameBoardXPath = '//*[@id="root"]/div/section';

change 
const coinElement = document.querySelector('div img[src^="/assets/MNT"]');
to
const coinElement = document.querySelector('div img[src^="/assets/6thCoin"]');

**Comment by pav18** [comment]
Thank you so much. Works but doesn't continue....  Need to press continue by myself

> change

**Comment by slukin1** [comment]
to auto-continue change corresponding xpath too
line 19 const gameBoardXPath
line 40 const gameBoardXPath
line 168 const gameBoardXPath

**Comment by pav18** [comment]
Of course, I did, but no result.

**Comment by slukin1** [comment]
fork bybit-autoclicker.user.js to your repository and change xpaths
and lines 9,10,11 to your repo address and update Violentmonkey to run your updated script. now it`s running from this repo without changed lines 40, 168

**Comment by pav18** [comment]
Still doesn't continue... Just waits for press

**Comment by slukin1** [comment]
Use console.log for debugging in JavaScript

**Comment by slukin1** [comment]
runned from your repo. it stop on Play Again.
Need to change in async function clickPlayAgainPeriodically()
const buttons = document.querySelectorAll('.btn.primary-btn');
to
const buttons = document.querySelectorAll('#root > div > div._gameEnd_8gxnp_1 > div > button');

**Comment by pav18** [comment]
> Use console.log for debugging in JavaScript

`
ByPass Telegram Web - BrewVNKHÔNG BÁN - SỬ DỤNG MIỄN PHÍTelegram: https://t.me/brewvn_ltd
index.ts:50 Supported image mime types Set(5)
index.ts:347 got state, time: 289.30000001192093
index.ts:490 Will mount IM page: 1733467881.942
peerLanguage.ts:92 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'message')
    at LP (peerLanguage.ts:92:63)
    at Vw (translatableMessage.ts:49:5)
    at translatableMessage.ts:178:12
    at c (solid.js:169:37)
    at ee (solid.js:773:17)
    at it (solid.js:173:12)
    at Ud (translatableMessage.ts:176:10)
    at hT.renderMessage (bubbles.ts:5694:9)
    at hT.safeRenderMessage (bubbles.ts:4990:34)
    at hT.processLocalMessageRender (bubbles.ts:8425:17)Understand this errorAI
content.js:22446 tgWebAppPlatform updated!
api.bybitcoinsweeper.com/api/users/me:1 
        
        
       Failed to load resource: the server responded with a status of 401 ()Understand this errorAI
api.bybitcoinsweeper.com/api/users/me:1 
        
        
       Failed to load resource: the server responded with a status of 401 ()Understand this errorAI
index-CblvDVWq.js:108 Something went wrong mounting the viewport Q0: Timeout reached: 1000ms
    at https://bybitcoinsweeper.com/assets/index-CblvDVWq.js:17:7890
(anonymous) @ index-CblvDVWq.js:108Understand this errorAI
index-CblvDVWq.js:108 `DialogContent` requires a `DialogTitle` for the component to be accessible for screen reader users.

If you want to hide the `DialogTitle`, you can wrap it with our VisuallyHidden component.

For more information, see https://radix-ui.com/primitives/docs/components/dialog
(anonymous) @ index-CblvDVWq.js:108Understand this errorAI
index-CblvDVWq.js:108 Warning: Missing `Description` or `aria-describedby={undefined}` for {DialogContent}.
(anonymous) @ index-CblvDVWq.js:108Understand this warningAI
Bybit Coinsweeper.user.js:146 Найдена монета: https://bybitcoinsweeper.com/assets/6thCoin.png
index-CblvDVWq.js:179 Clicked
index-CblvDVWq.js:179 Sound Played
Bybit Coinsweeper.user.js:151 Выполнен клик по монете после паузы в 4457.605597196156 мс
logger.ts:134 [0.024] [SW] init
logger.ts:134 [0.031] [SW] got 1 windows from the start
logger.ts:134 [0.031] [SW] window connected 61343d4b-6427-4ee2-8ba7-269ac1daaf3c windows before 0
logger.ts:134 [0.031] [SW] windows Array(0)
logger.ts:134 [0.032] [SW] sending message port for mtproto
index-CblvDVWq.js:108 `DialogContent` requires a `DialogTitle` for the component to be accessible for screen reader users.

If you want to hide the `DialogTitle`, you can wrap it with our VisuallyHidden component.

For more information, see https://radix-ui.com/primitives/docs/components/dialog
(anonymous) @ index-CblvDVWq.js:108
Qj @ index-CblvDVWq.js:64
Hk @ index-CblvDVWq.js:64
Wk @ index-CblvDVWq.js:64
Pk @ index-CblvDVWq.js:64
Ek @ index-CblvDVWq.js:64
jg @ index-CblvDVWq.js:62
(anonymous) @ index-CblvDVWq.js:64Understand this errorAI
index-CblvDVWq.js:108 Warning: Missing `Description` or `aria-describedby={undefined}` for {DialogContent}.
(anonymous) @ index-CblvDVWq.js:108
Qj @ index-CblvDVWq.js:64
Hk @ index-CblvDVWq.js:64
Wk @ index-CblvDVWq.js:64
Pk @ index-CblvDVWq.js:64
Ek @ index-CblvDVWq.js:64
jg @ index-CblvDVWq.js:62
(anonymous) @ index-CblvDVWq.js:64Understand this warningAI
index-CblvDVWq.js:108 `DialogContent` requires a `DialogTitle` for the component to be accessible for screen reader users.

If you want to hide the `DialogTitle`, you can wrap it with our VisuallyHidden component.

For more information, see https://radix-ui.com/primitives/docs/components/dialog
(anonymous) @ index-CblvDVWq.js:108
Qj @ index-CblvDVWq.js:64
Hk @ index-CblvDVWq.js:64
Wk @ index-CblvDVWq.js:64
Pk @ index-CblvDVWq.js:64
Ek @ index-CblvDVWq.js:64
jg @ index-CblvDVWq.js:62
(anonymous) @ index-CblvDVWq.js:64Understand this errorAI
index-CblvDVWq.js:108 Warning: Missing `Description` or `aria-describedby={undefined}` for {DialogContent}.
(anonymous) @ index-CblvDVWq.js:108
Qj @ index-CblvDVWq.js:64
Hk @ index-CblvDVWq.js:64
Wk @ index-CblvDVWq.js:64
Pk @ index-CblvDVWq.js:64
Ek @ index-CblvDVWq.js:64
jg @ index-CblvDVWq.js:62
(anonymous) @ index-CblvDVWq.js:64Understand this warningAI
`

**Comment by pav18** [comment]
>  Need to change 

Thank you so much. It works.

**Comment by slukin1** [comment]
I don`t know which Six we need to find
https://bybitcoinsweeper.com/assets/index-xmFDawbb.js
  NewCoin = "/assets/6thCoin.png"
  Coin6 = "/assets/Coin6.svg"
Seems like this: NewCoin

**Comment by pav18** [comment]
I would appreciate it if you contact me.. https://t.me/{remove}PAVchensky      pav18{remove}inbox    gmail     com
Just few questions if you don't mind

**Comment by slukin1** [comment]
Почем огурцы? 
В личку ответила. 
Мы вроде ничего секретного не обсуждаем, чтобы в личку переходить
Пробую переписать по новой. Правда javascript для меня несветлый лес
